### ISSUE TITLE
Privacy manifest files

### ISSUE THREAD

**Issue by MickaelTitecaTAO** [CommandersAct/tcconsent-flutter-plugin#4]
Hi,
Can you update this package in order to include [privacy manifests files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) ? 
They seem to be included in [5.4.6 of the iOSV5 repository](https://github.com/CommandersAct/iOSV5/releases/tag/5.4.6).
I hope you can release an update soon for this package.
Thanks,

**Comment by ahakimsaid** [comment]
Hi, 
Updates with the privacy manifest should be coming in the upcoming days. 
We're working on releasing them before Apple deadline.

**Comment by MickaelTitecaTAO** [comment]
Hi @ahakimsaid !
The [1.4.0](https://github.com/CommandersAct/tcconsent-flutter-plugin/releases/tag/1.4.0) adds privacy manifest files. I have updated my Flutter app with this version, but privacy manifest for TCConsent is incorrect. 
My app was rejected by Apple for this reason : 
```
ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/TCConsent.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty.
``` 
Can you fix it please ? 
Thanks,

**Comment by ahakimsaid** [comment]
Hi @MickaelTitecaTAO, 

Sorry for the late reply, i was out last week. 
We are aware of this problem and working on it on highest priority, the fix must be deployed into the native iOS SDK first, flutter SDK that depends on it will be right next in line.

Expect a new release soon. 
Cheers !

**Comment by ahakimsaid** [comment]
Hi @MickaelTitecaTAO , 
New version with correction is now available, check latest releases !

**Comment by MickaelTitecaTAO** [comment]
Works for me, thanks a lot @ahakimsaid !
